
name: deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: macos-10.14
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==0.16.3

      - name: compile md
        run: cd src && ./doc.py all

      - name: deploy to gh-pages
        run: mkdocs gh-deploy --clean
